name: competitor
description: A new sport app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  numberpicker: ^2.1.1
  youtube_player_flutter: ^8.0.0
  video_player: ^2.2.19
  image_picker: ^0.8.4+10
  time: ^2.1.0
  date_format: ^2.0.5
  firebase_core: ^1.2.1
  cloud_firestore: ^2.2.1
  firebase_storage: ^10.2.9
  firebase_auth: ^3.3.10
  cached_network_image: ^3.2.0
  firebase_database: ^9.0.8
  video_thumbnail: ^0.4.6
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1

flutter_native_splash:
  android: true
  ios: true

  color: "#000000"
  image: images/logo_rm.png

flutter:
  uses-material-design: true
  assets:
    - images/


